# =============================================
# Configuration Prometheus pour EPM Retail
# =============================================

global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'epm-retail'
    environment: 'production'

# Configuration des alertes
alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - alertmanager:9093

# Règles d'alerte
rule_files:
  - 'alerts.yml'

# Configuration du scraping
scrape_configs:
  # =============================================
  # Prometheus lui-même
  # =============================================
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # =============================================
  # API FastAPI
  # =============================================
  - job_name: 'epm-api'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['api:8000']
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: 'epm-api'

  # =============================================
  # PostgreSQL
  # =============================================
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres-exporter:9187']
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: 'epm-postgres'

  # =============================================
  # Redis
  # =============================================
  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: 'epm-redis'

  # =============================================
  # Node Exporter (métriques système)
  # =============================================
  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: 'epm-host'

  # =============================================
  # cAdvisor (métriques conteneurs)
  # =============================================
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: 'epm-containers'

# =============================================
# Configuration de stockage
# =============================================
storage:
  tsdb:
    path: /prometheus/data
    retention:
      time: 30d
      size: 10GB
